### ISSUE TITLE
error while loading mobileproxy.aar

### ISSUE THREAD

**Issue by namdroid** [Jigsaw-Code/outline-sdk#330]
at org.gradle.internal.execution.steps.IdentityCacheStep.lambda$executeDeferred$1(IdentityCacheStep.java:47)
	... 64 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, origin: /Users/ng/ourapp/mobileproxy/build/.transforms/df48ac59d92bcf85652c00a0b7530c3b/transformed/instrumented_jetified-mobileproxy-runtime.jar:go/Seq$GoRefQueue$1.class
	at Version.fakeStackEntry(Version_4.0.52.java:0)
	at com.android.tools.r8.internal.vk.a(R8_4.0.52_5a340ca2823c7e792fe09805c75f749b9d398d230bc0518bb54ae9b6b50addbe:75)

.........

com.android.tools.r8.internal.vk.b(R8_4.0.52_5a340ca2823c7e792fe09805c75f749b9d398d230bc0518bb54ae9b6b50addbe:2)
	at com.android.tools.r8.D8.run(R8_4.0.52_5a340ca2823c7e792fe09805c75f749b9d398d230bc0518bb54ae9b6b50addbe:11)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:120)
	... 153 more
Caused by: java.lang.NullPointerException

And:
> Transform mobileproxy.aar (project :mobileproxy) with DexingNoClasspathTransform
AGPBI: {"kind":"error","text":"java.lang.NullPointerException","sources":[{"file":"/Users/ng/ourapp/mobileproxy/mobileproxy/build/.transforms/df48ac59d92bcf85652c00a0b7530c3b/transformed/instrumented_jetified-mobileproxy-runtime.jar"}],"tool":"D8"}

Why NullPointerException ?

**Comment by jyyi1** [comment]
This might be caused by incompatible JDK used by gomobile and your Android app. Please make sure you are using JDK 11 when building the app.

**Comment by namdroid** [comment]
yes, the cause is that i have 2 different java version. thanks
